### ISSUE TITLE
`script-security` not processed

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/backend-extension-indexer#98]
### Reproduction steps

look at https://www.jenkins.io/doc/developer/extensions/

### Expected Results

something under `script-security`, e.g. for https://github.com/jenkinsci/script-security-plugin/blob/4778ca84bde5981deaea798db9d174bf0b93a7b0/src/main/java/org/jenkinsci/plugins/scriptsecurity/sandbox/Whitelist.java#L46

### Actual Results

no such plugin listed

### Anything else?

```
Failed to process script-security
java.lang.IllegalStateException: java.lang.NullPointerException
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.jenkinsci.extension_indexer.ExtensionPointsExtractor.extract(ExtensionPointsExtractor.java:68)
	at org.jenkinsci.extension_indexer.ExtensionPointsExtractor.extract(ExtensionPointsExtractor.java:40)
	at org.jenkinsci.extension_indexer.ExtensionPointListGenerator.discover(ExtensionPointListGenerator.java:338)
	at org.jenkinsci.extension_indexer.ExtensionPointListGenerator$2.run(ExtensionPointListGenerator.java:274)
```

**Comment by daniel-beck** [comment]
@timja Could you open a PR with java version 21 in the `Jenkinsfile`? Jesse suggests there may have been relevant javac fixes for his three issues.

**Comment by MarkEWaite** [comment]
Closing because there is now something under [script security](https://www.jenkins.io/doc/developer/extensions/script-security/)
