### ISSUE TITLE
`branch-api` not processed

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/backend-extension-indexer#99]
### Reproduction steps

check https://www.jenkins.io/doc/developer/extensions/scm-api/#scmhead-headbyitem

### Expected Results

https://github.com/jenkinsci/branch-api-plugin/blob/b4227cdbd5a2903adc7d5e3c7f2d67a690853392/src/main/java/jenkins/branch/BranchProjectFactory.java#L293 listed

### Actual Results

nothing there

### Anything else?

```
Failed to process branch-api
java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.hasTag(com.sun.tools.javac.code.TypeTag)" because the return value of "com.sun.tools.javac.code.Type$TypeVar.getUpperBound()" is null
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.analyze(JavacTaskImpl.java:383)
	at org.jenkinsci.extension_indexer.ExtensionPointsExtractor.extract(ExtensionPointsExtractor.java:68)
	at org.jenkinsci.extension_indexer.ExtensionPointsExtractor.extract(ExtensionPointsExtractor.java:40)
	at org.jenkinsci.extension_indexer.ExtensionPointListGenerator.discover(ExtensionPointListGenerator.java:338)
	at org.jenkinsci.extension_indexer.ExtensionPointListGenerator$2.run(ExtensionPointListGenerator.java:274)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.hasTag(com.sun.tools.javac.code.TypeTag)" because the return value of "com.sun.tools.javac.code.Type$TypeVar.getUpperBound()" is null
	at jdk.compiler/com.sun.tools.javac.code.Types.getBounds(Types.java:2732)
	at jdk.compiler/com.sun.tools.javac.comp.Check.checkNonCyclic1(Check.java:2394)
	at jdk.compiler/com.sun.tools.javac.comp.Check.checkNonCyclic(Check.java:2380)
```

**Comment by daniel-beck** [comment]
Resolved by #103.
